Always return server-timing header, even when there are errors
For some cases in the Minion, this is already logged when there are
failures:

    06:25:16.912 ERROR [grpc-default-executor-2] Error in cloud message receiver
    io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 500
    invalid content-type: text/html
    headers: Metadata(:status=500,date=Sun, 11 Jun 2023 06:25:16 GMT,content-type=text/html,content-length=170,strict-transport-security=max-age=15724800; includeSubDomains,server-timing=traceparent;desc="00-57a622d500e272e3fae60588b317763f-382ccb1d823a08e3-01")

This is very handy, because you can take the trace ID from the
traceparent in that server-timing header and go right to the trace
in Tempo. :)